// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_1qHjH-jgpAXPK_Au4l9Z4g1QK9jmauw',
    appId: '1:412398363285:android:917b108e673540e1e8b19c',
    messagingSenderId: '412398363285',
    projectId: 'recipe-94a61',
    databaseURL: 'https://recipe-94a61-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipe-94a61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAznuyuvFd8FMGEgXDlUJI--lLsNwWYeo',
    appId: '1:412398363285:ios:37e251be21993d9ee8b19c',
    messagingSenderId: '412398363285',
    projectId: 'recipe-94a61',
    databaseURL: 'https://recipe-94a61-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipe-94a61.appspot.com',
    androidClientId: '412398363285-ha30qk8rnnkitmjqtmo9k539kpv3ifvu.apps.googleusercontent.com',
    iosClientId: '412398363285-1ua4hhksh5sus70dq41ne4kav766paqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeapp',
  );

}